### ISSUE TITLE
[REQ] - Get-UebJob mod addition

### ISSUE THREAD

**Issue by MartynKeigher** [Unitrends/unitrends-pstoolkit#1]
Hey!

FIRST OFF..... EPIC Powershell mod Alberto!! I can see this being INCREDIBLY useful to assist with our monitoring of Unitrends jobs!  :+1: :+1: :+1: :+1:

Just wanted to know IF on the Get-UebJob module, there could be an additional field retrieved from the UEB?.. The field being 'Next run'.

Currently it brings back Schedule name, type, last status & (current) status only

://mk

**Comment by agonzalezm** [comment]
Thanks Martyn! Those properties are already there, but when you run the command only some common properties are shown in table by default.

Try the Format-list powershell cmdlet to see all properties

PS> get-uebjob | Format-List *

sid              : 1
id               : 1b
name             : Backup Job
type             : backup
app_id           : 40
system_name      : ueb08
description      : Backup Job
enabled          : 1
last_time        : 01/24/2016 03:00:00 am
next_time        : 01/25/2016 03:00:00 am
last_status      : Success
status           : Idle
calendar_str     : {Full: Sun-Sat at 03:00:00 am}
application_name : VMware

Or this command to show only the properties you want in table:

PS> get-uebjob | Format-Table name,next_time

name       next_time

---

Backup Job 01/25/2016 03:00:00 am

**Comment by MartynKeigher** [comment]
Hey Alberto!

Thanks for the prompt response!! Exactly what I was looking for! :) 

I'm going to be building out a few scripts with this for sure. I will let you know what I come up with!

://mk
