### ISSUE TITLE
Develop Start-UebRestoreJob.ps1 for File Level Restores

### ISSUE THREAD

**Issue by bobfrankly** [Unitrends/unitrends-pstoolkit#13]
The pull request was intended show that work is in progress on that cmdlet, but I don't think it's functional just yet. I 'm creating this 'issue' so we can track conversation and development on this and like cmdlets. Despite the age of my account, I'm very new (newb? 😆 ) to github and the processes within.

Original Pull Request: https://github.com/Unitrends/unitrends-pstoolkit/pull/11
API Reference: https://github.com/unitrends/unitrends-api-doc/wiki/post_restore_full

**Comment by agonzalezm** [comment]
I just commited fix for file-level restore. I was able to do a file-level restore using this command to restore administrator profile to c:\recover.

Start-UebRestoreJob -backupID 11017 -clientID 35 -includes "c:/users/Administrator/" -directory "c:/recover"

it doesnt preserver folder structure so if you are restoring multiple folder i guess you want to preserver the directoy structure.

You can get a list of all backupid for the asset using
Get-UebBackup -asset wir02

and clientid using 
get-uebcatalog

**Comment by bobfrankly** [comment]
Nice. I'm hoping to get it to the point where it'll take pipelined input from some of the other cmdlets. I'm working on expanding the parameter set, that'll help with things like the folder structure. 

Might also look at doing a confirmation prompt for an empty directory param. I'll have to see if there's a preferred way of handling that.

**Comment by agonzalezm** [comment]
I have renamed Start-UebRestoreJob to Start-UebRestoreFile, as i have created a new one Start-UebRestoreSQL for SQL server restores. Putting all in the same cmdlets is complex as they require different params, i think is better to have separate cmdlets for each application restores. Added also sample usage for Get-Help.

**Comment by eableson** [comment]
Quick note that there's an error handling the new flat option. When using the cmdlet, it systematically returns the following error :

`Invoke-RestMethod : {"timestamp":1490601580,"result":[{"message":"could not store value \"flat\": value must be Boolean"}]}`
`At C:\windows\system32\windowspowershell\v1.0\Modules\Unitrends\Modules\Helper.ps1:18 char:3`
`+         Invoke-RestMethod -Uri "https://$global:UebServer/$api" -Method Post -Headers  ...`
`+    ``~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException`
`    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by agonzalezm** [comment]
just fixed the issue and changed flat to bool, run update to get latest version and try again.
