### ISSUE TITLE
Job Tracking

### ISSUE THREAD

**Issue by bobfrankly** [Unitrends/unitrends-pstoolkit#14]
Would like to implement some job tracking, as the GUI is typically less then detailed.
Maybe just for file level restores, not sure.

Perhaps in a $global var, store:
- UEB Job ID
- (Get-Date)
- Restore Source Path
- Restore Target path
- ? Anything Else ?

**Comment by agonzalezm** [comment]
@bobfrankly what do you mean by job tracking? show some progress while a file job is running/being restored?

**Comment by bobfrankly** [comment]
@agonzalezm linking those parameters so that you get pull job details to see result related to job properties. Not sure it's an effective use of time, depends on how we'd link non-file restores to it. Nebulous idea at the moment :P

**Comment by agonzalezm** [comment]
Closing this as i think restore reports has all information you need and there is no need for this.
