### ISSUE TITLE
Get-UebInventory doesn't return nested objects

### ISSUE THREAD

**Issue by rukas** [Unitrends/unitrends-pstoolkit#17]
Hello,

When running Get-UebInventory, objects that are nested under a vCenter resource pool are not returned.  Objects show up in the protected assets section of the Web UI but do not show up when this command is run.  Please let me know if I can provide any additional details.

**Comment by agonzalezm** [comment]
Hi @Rukas, thanks for reporting this.

I have commited a change to use api/assets and that will return VMs under resource pool also. Could you run Update-UebPsToolkit or redownload last version and let me know if that works for you?

**Comment by rukas** [comment]
Hi @agonzalezm ,

Thanks for the quick reply.  This still does not appear to be working.  I think the issue here is that we have nested resource pools.  

An example is 
esx_host
    resource_pool1
        resource_pool2
            vm

**Comment by rukas** [comment]
Hi @agonzalezm,

After further review your change did actually fix the issue but the `Update-UebPsToolkit` cmdlet didn't work properly 

Instead of updating the modules in `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Unitrends\Modules` it put all of the new files under `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Unitrends\Unitrends`

I've created screenshots of the folder layout here: http://imgur.com/a/BtEWW 

Note: I ran the `Update-UebPsToolkit` as administrator and had no other PowerShell windows open when I updated.

I believe you can fix this by changing line 24 in Install.ps1 from 
`$destination = "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Unitrends"`
to
`$destination = "C:\Windows\System32\WindowsPowerShell\v1.0\Modules"`

**Comment by rukas** [comment]
Hi @agonzalezm,

Sorry for the plethora of comments on this but I found a bug introduced by the change you made.  The vCenter is one of the "nodes" that you initially loop through thus creating duplicate entries in the output of `Get-UebInventory` since servers are listed under the vCenter node and the individual vmware host nodes.

Thanks again!

**Comment by agonzalezm** [comment]
@Rukas  thanks i have fixed the install/update script.

I can list VM under nested resource pools.

About last comment if you have added vcenter and esx hosts also you will get duplicated but with different server name. I dont see how to avoid this. why are you adding both vcenter and esx standalone to ueb?

**Comment by rukas** [comment]
This was a recommendation from our Unitrends installation technician.  We're reviewing this with him now and hopefully will be removing the individual vSphere hosts.
