### ISSUE TITLE
[Feat.Rq.] Get asset Added/Installed date

### ISSUE THREAD

**Issue by MartynKeigher** [Unitrends/unitrends-pstoolkit#26]
Hey Alberto, 

Would it be possible to add 'InstalledDate' or 'AddedDate' as a property of the `Get-Inventory` or `Get-UebCatalog` cmdlets?? 

We recently had a client request this from us, and while you would think that 'earliest backup' would suffice - it's not what they are after, as those dates are actually different.

Thanks,

**Comment by agonzalezm** [comment]
The appliance doesnt expose the date when a client/asset was added/registered to protected assets list so un fortunately we cant provide that info in cmdlet.

Agree is not same as fist backup but just for curiosity what is the use case for this?

**Comment by MartynKeigher** [comment]
The use case:

When the client first signed up we sized the environment appropriately (from a storage perspective) and now they are running out of space that we first planned for.

We want to show the client that due to the un-expected, yet required addition, of 'these assets of these dates'...this is why we are not hitting the goals/expectations set during the initial sizing.

Thoughts..???

**Comment by MartynKeigher** [comment]
-bump-

**Comment by agonzalezm** [comment]
Not much we can do by now as the appliance doesnt keep track or exposes this so we cant access this info from API/powershell.

**Comment by MartynKeigher** [comment]
Fair enough. Not to worry. We'll document this another way then.

Thanks! :)
