### ISSUE TITLE
problem with powershell - command line : New-UebBackupJob

### ISSUE THREAD

**Issue by sylribeiro** [Unitrends/unitrends-pstoolkit#27]
Hi,
I want to create job with PowerShell.
But there is one error and after some tests I don't see where is the problem….

Command are :
PS C:\Windows\system32> New-UebBackupJob -Name "testjob2SR" -instances @('kompotest7-pc') -StartDate "2/27/2017" -StartTime "17:00" -BackupType Full -EmailAddresses @("sr@komposite.fr")

Error message:
Invoke-RestMethod : {"result":[{"code":"0","message":"No value provided for application ID.","link":"http:\/\/kb.unitrends.com"}]}
Au caractère C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Unitrends\Modules\Helper.ps1:18 : 3
+         Invoke-RestMethod -Uri "https://$global:UebServer/$api" -Method Post -Headers  ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Can you help me to resolve this problem?
Thank you in advance.

**Comment by sylribeiro** [comment]
up !

**Comment by agonzalezm** [comment]
Thanks for reporting this. This has been fixed problem was cmdlet supported only vm backup jobs, i have added support for file-level backups also. Update to last version and let me know if something goes wrong!
