### ISSUE TITLE
[Feat Rq.] Get Asset Number

### ISSUE THREAD

**Issue by MartynKeigher** [Unitrends/unitrends-pstoolkit#30]
Hey Alberto....

When I run the following command `Get-UebSystems | fl *` I get the following details...
```
id                : 1
host              : 100.10.10.1`
name              : Recovery01`
role              : Backup System`
version           : 9.1.1-2.201701181604.CentOS6`
version_status    : latest
online            : True
status            : available
customer_id       : 1
customer_name     : CLIENTNAME
location_id       : 1
location_name     : DataCenter
registered_assets : 66
replicating       : False
archiving         : False
local             : True
total_mb_size     : 3713734
total_mb_free     : 1413860
storage_name      : 
```

Would it be possible to add the `asset_tag` to this list of properties?? (The same as if you was doing `dpu asset` via SSH). If this is already done via a different cmdlet... then could you please point me in the right direction?? 

Thanks bud!

**Comment by MartynKeigher** [comment]
I have submitted #31 to handle this need. This can be closed when/if my PR is tested and merged into master. - Thanks.

**Comment by agonzalezm** [comment]
Thanks for PR, closing.
