### ISSUE TITLE
MSP License Count - Protect Assets

### ISSUE THREAD

**Issue by MartynKeigher** [Unitrends/unitrends-pstoolkit#32]
Hey Alberto, 

As an MSP, I have to retrieve the count given to me via this postgres command at the start of each month, for billing purposes.

```
psql -c postgres bpdb -c "select count(distinct s.instance_id) as protected_assets from bp.successful_backups s inner join bp.nodes n using(node_no) inner join bp.application_instances ai using (instance_id) inner join bp.application_lookup al using (app_id) where al.app_id in (50, 51, 40, 1) and (now()::date - 30) < (to_timestamp(s.start_time)::date);" | awk 'FNR == 3 {print $1}'
```

How can I use the PoSHToolkit to get that same value??

Here is a screenshot of the working command (yet I am unsure as to what 'accounts towards the value' of 17! Which 17??? lol)

![image](https://cloud.githubusercontent.com/assets/3298134/26412441/64b1995e-406e-11e7-9f53-3d3aa57772f5.png)

Thanks.

**Comment by agonzalezm** [comment]
@MartynKeigher  you will have to use plink ssh. If you look into Update-UebServer cmdlet with the ssh switch it uses this method. You can use same method as there to create a Run-UebSsh cmlet and run the cmd.

**Comment by MartynKeigher** [comment]
Thanks Alberto, 

So, I checked out the Update-UebServer cmdlet (thanks for pointing me in the right direction!! 

Pretty sure this is exactly what I need but now i'm fighting with escape characters in the postgres sql command that i need to send to the UEB. I'll play with it a bit more and if i can work something out I will let ya know! :) 

Thanks.

**Comment by MartynKeigher** [comment]
DONE!!! Check out PR #33 

Adjust/edit to your needs, but this worked for me! 

Thanks.
