### ISSUE TITLE
backup reporting

### ISSUE THREAD

**Issue by MartynKeigher** [Unitrends/unitrends-pstoolkit#5]
Hey, 

Is it possible to pull a count of success backup jobs _(in terms of VMs/agents)_ backed up, as opposed to number of successfully ran schedules?

My code so far is this...

`Get-UebJob | ?{$_.last_status -eq "Success" -and $_.last_time -gt (Get-Date).AddDays(-1) -and $_.name -NotMatch "Exec"} | Sort-Object last_time`

...and i get a list of successfully ran **schedules**, but what i would prefer is a list of successfully ran **backups**. 

I'm pretty sure i'm missing something simple, but any help would be appreciated!

Thanks.

**Comment by agonzalezm** [comment]
As we talked last night on the gitter channel "Get-UebJob -Recent"  is the way to get backup history list you need. 

Closing this issue :)

Alberto
